/* ============================================================
   TOKO ANOMALI — data.js
   Product data & image mapping
   ============================================================ */

const PRODUCTS = {
  gaming: [
    { id:'g1',  name:'Gaming Mouse Logitech',        desc:'12000 DPI, 7 tombol macro',              price:299000,  orig:420000,  badge:'BEST', img:'assets/GamingAccessories/HDMouseGaming Logitech.JPEG',  emoji:'🖱️' },
    { id:'g2',  name:'Keyboard Gamen-GK300 80%',     desc:'Switch Blue, RGB backlit',               price:449000,  orig:620000,  badge:'NEW',  img:'assets/GamingAccessories/HDKeyboard Gamen-GK300.JPEG',  emoji:'⌨️' },
    { id:'g3',  name:'Rexus Gaming Headset 7.1 Surround', desc:'Noise cancel mic, bass boost',           price:389000,  orig:540000,  badge:'HOT',  img:'assets/GamingAccessories/HDRexus Headset Gaming.JPEG',  emoji:'🎧' },
    { id:'g4',  name:'Mouse Pad XL Extended',       desc:'900×400mm, anti-slip base',             price:149000,  orig:220000,  badge:'SALE', img:'assets/GamingAccessories/HDMousepad Gaming.JPEG',  emoji:'🖱️' },
    { id:'g5',  name:'Homedoki Gaming Chair Pro',     desc:'Reclining 180°, lumbar support',         price:1899000, orig:2500000, badge:'BEST', img:'assets/GamingAccessories/HDHomedoki KursiGaming.JPEG',  emoji:'🪑' },
    { id:'g6',  name:'Joystick Controller HyperX',      desc:'Dual vibration, plug & play',            price:259000,  orig:360000,  badge:null,   img:'assets/GamingAccessories/HDController HyperX.JPEG',  emoji:'🕹️' },
    { id:'g7',  name:'Webcam Logitech-C922 PRO',          desc:'Auto focus, low-light OK',               price:349000,  orig:480000,  badge:'NEW',  img:'assets/GamingAccessories/HDWebcam Logitch-C922PRO.JPEG',  emoji:'📷' },
    { id:'g8',  name:'PlayStation 5',          desc:'Next-gen console, HDR Gaming, Slim form factor',               price:5676400,  orig:8900000,  badge:null,   img:'assets/GamingAccessories/HDPlayStation 5.JPEG',  emoji:'🔌' },
    { id:'g9',  name:'Compact Gaming Desk',        desc:'Sturdy steel frame, Space-saving design',               price:355200,  orig:480000, badge:'NEW',  img:'assets/GamingAccessories/HDMeja Gaming.JPEG',  emoji:'📹' },
    { id:'g10', name:'RGB lighting setup.JPEG',     desc:'RGB LED strip, 16 juta warna, music sync mode, & adjustable brightness',              price:129000,  orig:190000,  badge:null,   img:'assets/GamingAccessories/HDRGB lighting setup.JPEG', emoji:'💡' },
    { id:'g11', name:'PC Gaming Rakitan High-End',   desc:'AMD Ryzen 7/9 or Intel Core i7/i9 CPU, 32 GB DDR5 RAM, RTX 4080/RTX 5090 class GPU, 2 TB NVMe SSD, premium motherboard, liquid cooler, RGB case',                price:40700000,  orig:55000000, badge:'SALE', img:'assets/GamingAccessories/HDPC Rakitan Gaming.JPEG', emoji:'💾' },
    { id:'g12', name:'Cooling Pad Laptop 2 Fan',   desc:'2 kipas, LED biru, 2 USB',               price:149000,  orig:220000,  badge:null,   img:'assets/GamingAccessories/HDStand Cooling Pad.JPEG', emoji:'❄️' },
    { id:'g13', name:'Microphone ROG Carnyx',   desc:'Condenser, cardioid pickup',              price:499000,  orig:700000,  badge:'HOT',  img:'assets/GamingAccessories/HDMicrophone ROG Carnyx.JPEG', emoji:'🎤' },
    { id:'g14', name:'Laptop Lenvo LOQ RTX 5050',   desc:'100x60cm, steel frame, cable hole, smooth surface, laptop + monitor space',            price:12888000,  orig:17900000,  badge:'NEW',  img:'assets/GamingAccessories/HDLaptop Lenovo LOQ.JPEG', emoji:'🖥️' },
    { id:'g15', name:'Xbox Series X',        desc:'1TB SSD, 4K gaming, 120FPS support, ray tracing, HDMI 2.1, quick resume',            price:6630000,  orig:8500000, badge:'SALE', img:'assets/GamingAccessories/HDXbox Series X.JPEG', emoji:'🎮' },
    { id:'g16', name:'Laptop Asus ROG Strix G16',     desc:'Intel Core i7, 16GB RAM, RTX 4060, 16″ QHD 165Hz, 1TB SSD, RGB keyboard',          price:21280000,  orig:28000000,  badge:'NEW',  img:'assets/GamingAccessories/Asus ROG Strix-G16.JPEG', emoji:'⌨️' },
    { id:'g17', name:'Gaming Monitor SUIRGE',   desc:'27″ FHD/IPS, 165Hz refresh, 1ms response, FreeSync/G-Sync compatible, slim bezel',            price:2499000, orig:3200000, badge:'HOT',  img:'assets/GamingAccessories/HDMonitor SUIRGE.JPEG', emoji:'🖥️' },
    { id:'g18', name:'ROG Phone 9 PRO',      desc:'Snapdragon 8s Gen3, 512GB/1TB, 6.78″ 165Hz AMOLED, 6000mAh, AirTrigger 2',                 price:19250000,  orig:25000000,  badge:'BEST', img:'assets/GamingAccessories/HDROG Phone 9 Pro.JPEG', emoji:'🖱️' },
    { id:'g19', name:'Powerbank high capacity',desc:'20,000–30,000 mAh, dual USB-C + USB-A, fast charging, LED indicator, compact design',             price:532500,   orig:750000,  badge:null,   img:'assets/GamingAccessories/HDPowerbank high capacity.JPEG', emoji:'📦' },
    { id:'g20', name:'Gamen Earphone',  desc:'In-ear gaming earphones, low latency, built-in mic, braided cable, enhanced bass',                price:276500,  orig:350000,  badge:null,   img:'assets/GamingAccessories/HDGamen Earphone.JPEG', emoji:'🌀' },
    { id:'g21', name:'Nintendo Switch',      desc:'Hybrid portable/home console, Joy-Con controllers, 6.2″ LCD, dockable TV mode',               price:4235000,  orig:5500000,  badge:null,   img:'assets/GamingAccessories/HDNintendoSwitch.JPEG', emoji:'🖐️' },
    { id:'g22', name:'Dual Monitor Arm',           desc:'Gas spring, 360° rotation',               price:699000,  orig:950000,  badge:'SALE', img:'assets/GamingAccessories/HDDual Monitor Arm.JPEG', emoji:'🖥️' },
    { id:'g23', name:'Surround Sound Speaker 2.1', desc:'Subwoofer, Bluetooth + 3.5mm',            price:549000,  orig:750000,  badge:'NEW',  img:'assets/GamingAccessories/HDSpeaker gaming.JPEG', emoji:'🔊' },
    { id:'g24', name:'Cooling Fan HP',   desc:'USB powered, dual fans, adjustable height, anti-slip pad, quiet operation',          price:262500,  orig:350000,  badge:null,   img:'assets/GamingAccessories/HDCooling fan HP.JPEG', emoji:'👓' },
    { id:'g25', name:'Dual Sense Edge',     desc:'Wireless pro controller, customizable back buttons, swappable stick caps, haptic feedback, USB-C',           price:2920000,   orig:4000000,  badge:null,   img:'assets/GamingAccessories/HDDualSense Edge.JPEG', emoji:'🔗' },
  ],
  beauty: [
    { id:'b1',  name:'Vitamin C Serum 20%',        desc:'Brightening & anti-aging, 30ml',         price:189000,  orig:280000,  badge:'BEST', img:'assets/GamingAccessories/BeautyItems/vitaminc.jpeg',  emoji:'✨' },
    { id:'b2',  name:'Hyaluronic Moisturizer',     desc:'Deep hydration 72 jam, 50ml',            price:219000,  orig:300000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/hyaluronic.jpeg',  emoji:'💧' },
    { id:'b3',  name:'Niacinamide 10% Serum',      desc:'Pore minimizer, oil control',            price:149000,  orig:220000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/niacinamide10.jpeg',  emoji:'🧴' },
    { id:'b4',  name:'Retinol Night Cream',        desc:'Anti-wrinkle, regenerasi malam',         price:279000,  orig:380000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/retinolnight.jpeg',  emoji:'🌙' },
    { id:'b5',  name:'SPF 50+ Sunscreen PA++++',  desc:'Water resistant, ringan di kulit',        price:129000,  orig:180000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/spf50.jpeg',  emoji:'☀️' },
    { id:'b6',  name:'Toner AHA BHA Exfoliating', desc:'Chemical exfoliant, 150ml',               price:169000,  orig:240000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/toneraha.jpeg',  emoji:'💫' },
    { id:'b7',  name:'Mugwort Calming Ampoule',   desc:'Soothing & anti-redness, 30ml',           price:199000,  orig:280000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/mugwort.jpeg',  emoji:'🌿' },
    { id:'b8',  name:'Face Wash Salicylic Acid',  desc:'Acne fighting, 100ml gentle',              price:99000,   orig:150000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/facewashsali.jpeg',  emoji:'🫧' },
    { id:'b9',  name:'Eye Cream Peptide Complex', desc:'Anti dark circle, lifting 15ml',           price:249000,  orig:340000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/eyecream.jpeg',  emoji:'👁️' },
    { id:'b10', name:'Sheet Mask Collagen Pack',  desc:'5 lembar, brightening & plump',            price:89000,   orig:140000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/sheetmask.jpeg', emoji:'😷' },
    { id:'b11', name:'Snail Mucin 96% Essence',   desc:'Repair & glow, 100ml',                    price:219000,  orig:300000,  badge:'BEST', img:'assets/GamingAccessories/BeautyItems/snailmucin.jpeg', emoji:'🐌' },
    { id:'b12', name:'Ceramide Barrier Cream',    desc:'Skin repair, 50ml rich texture',           price:259000,  orig:350000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/ceramidebarrier.jpeg', emoji:'🛡️' },
    { id:'b13', name:'Rose Hip Oil Cold Pressed', desc:'Natural 30ml, anti pigmentasi',            price:189000,  orig:270000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/rosehip.jpeg', emoji:'🌹' },
    { id:'b14', name:'Tranexamic Acid Serum',     desc:'Hyperpigmentation treatment',              price:239000,  orig:330000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/tranexamic.jpeg', emoji:'⚗️' },
    { id:'b15', name:'Skincare Starter Kit Bundle',desc:'5 produk essential, hemat 35%',          price:499000,  orig:750000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/starterkit.jpeg', emoji:'🎁' },
    { id:'b16', name:'Micellar Water Cleansing',  desc:'Double cleansing, 200ml gentle',           price:109000,  orig:160000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/micellarwater.jpeg', emoji:'💦' },
    { id:'b17', name:'Lip Serum Plumping',        desc:'Hyaluronic + Peptide, 10ml',              price:139000,  orig:200000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/plumpinglip.jpeg', emoji:'💋' },
    { id:'b18', name:'Under Eye Gel Patch 60pcs', desc:'Gold collagen, depuff instantly',          price:179000,  orig:250000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/undereye.jpeg', emoji:'👁️' },
    { id:'b19', name:'Gua Sha Jade Stone',        desc:'Facial massage, anti puffiness',          price:129000,  orig:190000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/guasha.jpeg', emoji:'🪨' },
    { id:'b20', name:'Facial Mist Rosewater',     desc:'Refreshing spray, 100ml travel',          price:99000,   orig:150000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/rosewater.jpeg', emoji:'🌸' },
    { id:'b21', name:'Benzoyl Peroxide 5% Gel',   desc:'Spot treatment, acne fighter',            price:89000,   orig:130000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/benzoyl.jpeg', emoji:'💊' },
    { id:'b22', name:'Peptide Anti Aging Serum',  desc:'Multi-peptide, firming 30ml',             price:319000,  orig:450000,  badge:'BEST', img:'assets/GamingAccessories/BeautyItems/peptideanti.jpeg', emoji:'⚗️' },
    { id:'b23', name:'Exfoliating Body Scrub',    desc:'Coffee & sugar scrub, 200g',              price:119000,  orig:170000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/bodyscrub.jpeg', emoji:'☕' },
    { id:'b24', name:'Facial Oil Marula Pure',    desc:'Lightweight dry oil, 30ml luxury',        price:289000,  orig:400000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/marula.jpeg', emoji:'🫙' },
    { id:'b25', name:'K-Beauty Routine Bundle',   desc:'7 produk Korean skincare set',            price:699000,  orig:1000000, badge:'SALE', img:'assets/GamingAccessories/BeautyItems/k-beauty.jpeg', emoji:'🇰🇷' },
  ],
  fashion: [
    { id:'f1',  name:'Kaos Oversize Vintage',     desc:'Cotton 240gsm, unisex premium',           price:189000,  orig:250000,  badge:'BEST', img:'assets/GamingAccessories/BeautyItems/CoolClothes/oversize.jpeg', emoji:'🧥' },
    { id:'f3',  name:'Hoodie Streetwear Fleece',  desc:'Fleece tebal, inner premium',             price:349000,  orig:450000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/hoodie.jpeg', emoji:'🧣' },
    { id:'f4',  name:'Celana Cargo Tactical',     desc:'6 kantong ripstop, comfy fit',            price:299000,  orig:399000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/tactical.jpeg', emoji:'👖' },
    { id:'f5',  name:'Jaket Bomber PU Leather',   desc:'Kulit sintetik, inner fleece',            price:499000,  orig:699000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/bomber.jpeg', emoji:'🧥' },
    { id:'f6',  name:'Polo Shirt Pique Premium',  desc:'Bahan pique, formal casual',              price:199000,  orig:280000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/poloshirt.jpeg', emoji:'👔' },
    { id:'f7',  name:'Sweater Rajut Cozy',        desc:'Knit wool blend, warm & comfy',           price:319000,  orig:420000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/sweater.jpeg', emoji:'🧶' },
    { id:'f8',  name:'Celana Chino Slim Stretch', desc:'Stretch chino, wrinkle resist',           price:249000,  orig:330000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/chino.jpeg', emoji:'👖' },
    { id:'f9',  name:'Jaket Parasut Windbreaker', desc:'Water resistant, slim pack',              price:279000,  orig:380000,  badge:'BEST', img:'assets/GamingAccessories/BeautyItems/CoolClothes/jaketparasut.jpeg', emoji:'🧥' },
    { id:'f10', name:'Kemeja Linen Casual',       desc:'Linen murni, adem & stylish',             price:229000,  orig:300000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/linen.jpeg',emoji:'👔' },
    { id:'f11', name:'Cardigan Crop Rajut',       desc:'Ribbed knit, cropped style',              price:279000,  orig:380000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/cardigan.jpeg',emoji:'🧶' },
    { id:'f12', name:'Track Pants Retro Panel',   desc:'Panel samping, 80s aesthetic',            price:209000,  orig:280000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/trackpants.jpeg',emoji:'👖' },
    { id:'f13', name:'Turtleneck Ribbed Knit',    desc:'Ribbed stretch, semua ukuran',            price:249000,  orig:340000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/turtleneck.jpeg',emoji:'🧣' },
    { id:'f14', name:'Jaket Denim Vintage Patch', desc:'Denim wash, patch decoratif',             price:389000,  orig:520000,  badge:'BEST', img:'assets/GamingAccessories/BeautyItems/CoolClothes/jaketdenim.jpeg',emoji:'🧥' },
    { id:'f15', name:'Kaos Basic 3-Pack Bundle',  desc:'3 kaos basic cotton 200gsm',              price:219000,  orig:320000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/CoolClothes/3-pack.jpeg',emoji:'👕' },
    { id:'f16', name:'Celana Jogger Fleece',      desc:'Tapered fit, elastic waist',              price:229000,  orig:310000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/jogger.jpeg',emoji:'👖' },
    { id:'f17', name:'Kemeja Oxford Classic',     desc:'100% cotton Oxford weave',                price:269000,  orig:360000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/oxford.jpeg',emoji:'👔' },
    { id:'f18', name:'Rok Mini Pleated',          desc:'A-line pleat, high waist',                price:199000,  orig:270000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/rokmini.jpeg',emoji:'👗' },
    { id:'f19', name:'Celana Wide Leg Linen',     desc:'Flowy linen, breezy comfort',             price:259000,  orig:350000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/celanawide.jpeg',emoji:'👖' },
    { id:'f20', name:'Kemeja Batik Modern',       desc:'Motif kontemporer, slim cut',             price:299000,  orig:400000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/batik.jpeg',emoji:'🎨' },
    { id:'f21', name:'Varsity Jacket Wool',       desc:'Varsity patch, rib cuffs',                price:599000,  orig:800000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/varsity.jpeg',emoji:'🧥' },
    { id:'f22', name:'Crop Top Ribbed Knit',      desc:'Stretchy rib, boxy cropped',              price:149000,  orig:210000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/croptop.jpeg',emoji:'👕' },
    { id:'f23', name:'Celana Pendek Cargo',       desc:'6-pocket cargo shorts, ripstop',         price:199000,  orig:270000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/cargopendek.jpeg',emoji:'🩳' },
    { id:'f24', name:'Outer Longline Blazer',     desc:'Structured lapel, oversized fit',         price:449000,  orig:620000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/CoolClothes/outer.jpeg',emoji:'🧥' },
    { id:'f25', name:'Street Style Bundle Set',  desc:'Hoodie + Cargo + Tee combo deal',          price:649000,  orig:920000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/CoolClothes/streetstyle.jpeg',emoji:'🛍️' },
  ],
  electronic: [
    { id:'e1',  name:'AC Split Daikin 1 PK',          desc:'Inverter, hemat listrik, wifi control, freon R32',              price:4299000,  orig:5800000,  badge:'BEST', img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/acdaikin.jpeg',       emoji:'❄️' },
    { id:'e2',  name:'Kulkas 2 Pintu Samsung 400L',   desc:'Twin Cooling Plus, No Frost, Energy Star A++',                  price:5499000,  orig:7200000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/kulkassamsung.jpeg',  emoji:'🧊' },
    { id:'e3',  name:'Mesin Cuci LG Front Load 9kg',  desc:'Steam wash, inverter direct drive, 1400 RPM',                   price:6299000,  orig:8500000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/mesincucilg.jpeg',   emoji:'👕' },
    { id:'e4',  name:'TV LED Samsung 55" 4K Smart',   desc:'Crystal UHD, HDR10+, Tizen OS, Dolby Audio',                   price:7499000,  orig:9900000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/tvsamsung.jpeg',      emoji:'📺' },
    { id:'e5',  name:'Kulkas Mini 1 Pintu 90L',       desc:'Hemat listrik, cocok kos/kamar, bebas freon CFC',               price:1299000,  orig:1800000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/kulkasmini.jpeg',    emoji:'🧊' },
    { id:'e6',  name:'Kipas Angin Stand Panasonic',   desc:'5 daun baling, 3 kecepatan, timer, swing otomatis',             price:449000,   orig:620000,   badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/kipaspanasonic.jpeg', emoji:'🌀' },
    { id:'e7',  name:'Water Dispenser Galon Bawah',   desc:'Hot & cool & normal, galon bawah, stainless tank',              price:1199000,  orig:1700000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/dispenser.jpeg',       emoji:'🚰' },
    { id:'e8',  name:'Rice Cooker Philips 1.8L',      desc:'Fuzzy logic, warm otomatis, anti lengket tebal',                price:599000,   orig:850000,   badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/ricecooker.jpeg',    emoji:'🍚' },
    { id:'e9',  name:'Setrika Uap Philips 2400W',     desc:'Steam boost 210g/min, anti-scale, soleplate titanium',          price:699000,   orig:1000000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/setrika.jpeg',        emoji:'👔' },
    { id:'e10', name:'Vacuum Cleaner Electrolux 1600W',desc:'HEPA filter, daya hisap kuat, bagless canister',               price:1499000,  orig:2100000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/vacuum.jpeg',         emoji:'🌪️' },
    { id:'e11', name:'Blender Philips Pro 2L',        desc:'600W, pisau stainless, jar kaca, 3 kecepatan + pulse',          price:529000,   orig:750000,   badge:'BEST', img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/blender.jpeg',        emoji:'🍹' },
    { id:'e12', name:'Microwave Sharp 22L',           desc:'Grill + microwave combo, 800W, 5 power level, timer',          price:1099000,  orig:1550000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/microwave.jpeg',      emoji:'📡' },
    { id:'e13', name:'Mesin Cuci Top Load Sanyo 8kg', desc:'Fuzzy logic, 8 program cuci, hemat air & listrik',              price:2799000,  orig:3900000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/mesincucitop.jpeg', emoji:'🫧' },
    { id:'e14', name:'TV LED LG 43" Full HD Smart',   desc:'WebOS, ThinQ AI, HDR Active, Dolby Audio, 60Hz',               price:4299000,  orig:5700000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/tvlg.jpeg',          emoji:'📺' },
    { id:'e15', name:'Oven Toaster Cosmos 25L',       desc:'Pemanggang + oven, 1500W, 6 fungsi, timer 60 menit',           price:799000,   orig:1150000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/oven.jpeg',           emoji:'🥐' },
    { id:'e16', name:'Air Fryer Philips 4.1L',        desc:'Rapid Air Technology, -80% minyak, digital panel',             price:1299000,  orig:1850000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/airfryer.jpeg',      emoji:'🍟' },
    { id:'e17', name:'Pompa Air Submersible DAB',     desc:'Daya 370W, max head 30m, stainless, cocok sumur 4"',           price:1499000,  orig:2100000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/pompaair.jpeg',     emoji:'💧' },
    { id:'e18', name:'Exhaust Fan Panasonic 6"',      desc:'Silent, hemat listrik, cocok dapur/kamar mandi',               price:349000,   orig:480000,   badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/exhaustfan.jpeg',   emoji:'💨' },
    { id:'e19', name:'Water Heater Ariston 15L',      desc:'Tangki email anti karat, safety valve, 350W',                  price:1799000,  orig:2500000,  badge:'HOT',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/waterheater.jpeg',  emoji:'🚿' },
    { id:'e20', name:'Speaker Aktif Polytron 12"',    desc:'300W PMPO, Bluetooth, USB/SD, FM Radio, karaoke',              price:899000,   orig:1300000,  badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/speaker.jpeg',       emoji:'🔊' },
    { id:'e21', name:'Juicer Buah Sayur Philips',     desc:'800W, pulp container, mudah dibersihkan, multi fungsi',        price:699000,   orig:1000000,  badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/juicer.jpeg',        emoji:'🍊' },
    { id:'e22', name:'AC Portable Sharp 1 PK',       desc:'Tanpa instalasi, 3 mode, timer, cocok ruangan 10–14m²',        price:3499000,  orig:4800000,  badge:'BEST', img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/acportable.jpeg',   emoji:'❄️' },
    { id:'e23', name:'Kulkas Side by Side LG 600L',  desc:'InstaView Door-in-Door, wifi, ice maker, A+ energy',           price:12499000, orig:17000000, badge:'NEW',  img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/kulkassbs.jpeg',    emoji:'🧊' },
    { id:'e24', name:'Dispenser Galon Atas Miyako',   desc:'Hot & cool, indicator lampu, mudah diisi ulang',               price:349000,   orig:500000,   badge:null,   img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/dispensermiyako.jpeg',emoji:'🚰' },
    { id:'e25', name:'Paket Hemat Elektronik Dapur',  desc:'Rice cooker + blender + teko listrik combo, hemat 30%',        price:1199000,  orig:1750000,  badge:'SALE', img:'assets/GamingAccessories/BeautyItems/CoolClothes/ElectronicDevices/paketdapur.jpeg',   emoji:'🏠' },
  ]
};

// Featured products (2 from each category)
const FEATURED = [
  { ...PRODUCTS.gaming[0] },
  { ...PRODUCTS.gaming[2] },
  { ...PRODUCTS.beauty[0] },
  { ...PRODUCTS.beauty[3] },
  { ...PRODUCTS.fashion[0] },
  { ...PRODUCTS.fashion[2] },
  { ...PRODUCTS.electronic[0] },
  { ...PRODUCTS.electronic[2] },
];

const CATEGORY_LABELS = {
  gaming:    '🎮 Gaming Accessories',
  beauty:    '✨ Beauty Items',
  fashion:   '👗 Cool Clothes',
  electronic:'📱 Electronic Devices',
};